env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  semi: ["warn", "always"]
}
